cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 20020101T000000Z
  end: 20210101T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/hirs/1bhrs4/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.1bhrs4.tm00.bufr_d

