cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19981026T000000Z
  end: 20140616T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/amsub/1bamub/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.1bamub.tm00.bufr_d

