cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 20091001T000000Z
  end: 20210101T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/ssmis/ssmisu/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.ssmisu.tm00.bufr_d

