cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19790101T000000Z
  end:   20050805T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/ssu/1bssu/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.1bssu.tm00.bufr_d

