cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 20010301T000000Z
  end: 20120301T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/avhrr/nasa/21cr_repro/avcspm/%Y/%m/bufr/gmao.%Y%m%d.t%Hz.avcspm.tm00.bufr_d

