cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 20170201T000000Z
  end: 20210101T180000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/saphir/saphir/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.saphir.tm00.bufr_d

