cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19981026T000000Z
  end: 20090501T060000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/amsua/nasa/r21c_repo/%Y/%m/bufr/gmao_r21c_repro.%Y%m%d.t%Hz.1bamu.tm00.bufr

