cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 20070201T000000Z
  end: 20210101T180000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/airs/airsev/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.airsev.tm00.bufr_d

