cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19981026T000000Z
  end: 20210101T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/amsua/1bamua/%Y/%m/bufr/gdas.%Y%m%d.t%Hz.1bamua.tm00.bufr_d

