cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19991015T000000Z
  end: 20181217T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/ozone/nasa/sbuv_v87/%Y/%m/bufr/sbuv_v87.%Y%m%d.t%Hz.bufr

