cycling_interval: 21600
date_range:
  datestr: '%Y%m%dT%H%M%SZ'
  start: 19790101T000000Z
  end: 20231101T000000Z
search_info:
  -
    platform: aws_s3_clean
    key: observations/reanalysis/conv/prepbufr/%Y/%m/prepbufr/gdas.%Y%m%d.t%Hz.prepbufr.nr

